name: Release

on: 
  push:
    tags: ['*']

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Deno
        uses: denoland/setup-deno@v1
      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/deno
          key: deno-${{hashFiles('deno.lock')}}
          restore-keys: deno-
      - name: Build artifacts
        run: |-
          deno task build --target=x86_64-unknown-linux-gnu -o poe-discord-rpc-linux
          deno task build --target=x86_64-pc-windows-msvc -o poe-discord-rpc-win.exe
          deno task build --target=x86_64-apple-darwin -o poe-discord-rpc-mac
          deno task build --target=aarch64-apple-darwin -o poe-discord-rpc-mac-m1
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: poe-discord-rpc-*
