name: Release

on:
  push:
    tags: ['*']

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Deno
        uses: denoland/setup-deno@v1
      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/deno
          key: deno-${{hashFiles('deno.lock')}}
          restore-keys: deno-
      - name: Build artifacts
        run: |-
          TARGET=x86_64-unknown-linux-gnu SUFFIX=linux deno task build
          TARGET=x86_64-pc-windows-msvc SUFFIX=win.exe deno task build
          TARGET=x86_64-apple-darwin SUFFIX=mac deno task build
          TARGET=aarch64-apple-darwin SUFFIX=mac-m1 deno task build
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: poe-discord-rpc-*
